---
- name: Ensure that the tftp-server package is installed
  tags: tftp-server
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: tftp_server_yum
  with_items:
    - tftp
    - tftp-server

- name: Attempting to overlay tftp-server configurations
  tags: tftp-server
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: tftp.j2, dst: /etc/xinetd.d/tftp }
  when: tftp_server_yum is success

- name: Ensure that tftp-server is started and enabled on boot
  tags: tftp-server
  become: true
  service:
    enabled: yes
    name: xinetd
    state: started
  when: tftp_server_yum is success
...
