---
- name: Ensure that the tftp-server package is installed
  tags: tftp-server
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  register: tftp_server_yum
  with_items:
    - tftp
    - tftp-server

- block:
    - name: Applying tftp-server configuration
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        owner: root
        group: root
        mode: 0644
      notify: restart xinetd
      with_items:
        - { src: tftp.j2, dst: /etc/xinetd.d/tftp }

    - name: Enable and start the xinetd service
      service:
        enabled: yes
        name: xinetd
        state: started
  tags: tftp-server
  when: tftp_server_yum|success
...
